AWSTemplateFormatVersion: '2010-09-09'
Description: 'SageMaker Unified Studio Domain - Minimal version with just the domain'

Parameters:
  DomainName:
    Type: String
    Description: Name of the SageMaker Unified Studio domain
    Default: "Corporate-Test"
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '^[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9]$'
    ConstraintDescription: Domain name must be 1-64 characters, start and end with alphanumeric, and contain only alphanumeric characters and hyphens

  DomainDescription:
    Type: String
    Description: Description for the SageMaker Unified Studio domain
    Default: "SageMaker Unified Studio domain for testing CloudFormation deployment"
    MaxLength: 2048

  DomainExecutionRole:
    Type: String
    Description: IAM role ARN for domain execution
    Default: "arn:aws:iam::000557565608:role/service-role/AmazonSageMakerDomainExecution"
    AllowedPattern: '^arn:aws:iam::[0-9]{12}:role/.*$'
    ConstraintDescription: Must be a valid IAM role ARN

  ServiceRole:
    Type: String
    Description: IAM service role ARN for the domain
    Default: "arn:aws:iam::000557565608:role/service-role/AmazonSageMakerDomainService"
    AllowedPattern: '^arn:aws:iam::[0-9]{12}:role/.*$'
    ConstraintDescription: Must be a valid IAM role ARN

  SSOUserAssignment:
    Type: String
    Description: Single Sign-On user assignment method
    Default: "MANUAL"
    AllowedValues:
      - "AUTOMATIC"
      - "MANUAL"

  IDCInstanceArn:
    Type: String
    Description: AWS IAM Identity Center instance ARN (optional)
    Default: "arn:aws:sso:::instance/ssoins-790730fbc9d864c7"
    AllowedPattern: '^(arn:aws:sso:::instance/ssoins-[a-z0-9]{16})?$'
    ConstraintDescription: Must be a valid IAM Identity Center instance ARN or empty

Conditions:
  HasIDCInstance: !Not [!Equals [!Ref IDCInstanceArn, ""]]

Resources:
  # Main SageMaker Unified Studio Domain
  SageMakerUnifiedStudioDomain:
    Type: AWS::DataZone::Domain
    Properties:
      Name: !Ref DomainName
      Description: !Ref DomainDescription
      DomainExecutionRole: !Ref DomainExecutionRole
      DomainVersion: "V2"
      ServiceRole: !Ref ServiceRole
      SingleSignOn:
        Type: "IAM_IDC"
        UserAssignment: !Ref SSOUserAssignment
        IdcInstanceArn: !If
          - HasIDCInstance
          - !Ref IDCInstanceArn
          - !Ref AWS::NoValue
      Tags:
        - Key: "Environment"
          Value: "Test"
        - Key: "Purpose"
          Value: "SageMaker Unified Studio"
        - Key: "CreatedBy"
          Value: "CloudFormation"

Outputs:
  DomainId:
    Description: "SageMaker Unified Studio Domain ID"
    Value: !Ref SageMakerUnifiedStudioDomain
    Export:
      Name: !Sub "${AWS::StackName}-DomainId"

  DomainArn:
    Description: "SageMaker Unified Studio Domain ARN"
    Value: !GetAtt SageMakerUnifiedStudioDomain.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DomainArn"

  DomainName:
    Description: "SageMaker Unified Studio Domain Name"
    Value: !Ref DomainName
    Export:
      Name: !Sub "${AWS::StackName}-DomainName"

  PortalUrl:
    Description: "SageMaker Unified Studio Portal URL"
    Value: !GetAtt SageMakerUnifiedStudioDomain.PortalUrl
    Export:
      Name: !Sub "${AWS::StackName}-PortalUrl"

  RootDomainUnitId:
    Description: "Root Domain Unit ID"
    Value: !GetAtt SageMakerUnifiedStudioDomain.RootDomainUnitId
    Export:
      Name: !Sub "${AWS::StackName}-RootDomainUnitId"
